# Generated by Django 4.1.3 on 2023-03-30 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0002_entry_bibiliography_remove_entry_entryauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entryauthor',
            field=models.ManyToManyField(blank=True, to='thesearchable.author'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
