# Generated by Django 4.1.3 on 2023-04-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0003_alter_entry_entryauthor_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
