# Generated by Django 4.1.3 on 2023-04-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0004_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entryCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesearchable.categories'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entryClassification',
            field=models.ManyToManyField(blank=True, null=True, to='thesearchable.classification'),
        ),
    ]
