# Generated by Django 4.1.3 on 2023-04-25 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0007_remove_entry_downloadeduser_remove_entry_viewedusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='favouriteusers',
            field=models.ManyToManyField(blank=True, related_name='favouriteusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
