# Generated by Django 4.1.3 on 2023-04-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0009_entry_viewscounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='lastDatePayment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
