# Generated by Django 4.1.3 on 2023-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0010_userinfo_lastdatepayment_userinfo_lastpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='approvedcategories',
            field=models.ManyToManyField(blank=True, null=True, to='thesearchable.categories'),
        ),
    ]
