# Generated by Django 4.1.3 on 2023-04-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0013_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
