# Generated by Django 4.1.3 on 2023-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0014_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
