# Generated by Django 4.1.3 on 2023-04-30 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thesearchable.models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0015_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=thesearchable.models.upload_to)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
