# Generated by Django 4.1.3 on 2023-05-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0016_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='creator',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='search'),
        ),
    ]
