# Generated by Django 4.1.3 on 2023-05-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0017_remove_mymodel_creator_alter_mymodel_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
