# Generated by Django 4.1.3 on 2023-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0018_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookClassification',
            field=models.ManyToManyField(blank=True, to='thesearchable.classification'),
        ),
    ]
