# Generated by Django 4.1.3 on 2023-05-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0019_book_bookclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookOrigin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesearchable.countries'),
        ),
    ]
