# Generated by Django 4.1.3 on 2023-06-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0021_ocrbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='submittedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubmittedAuthorUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='submittedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submittedBookUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='submittedAuthors',
            field=models.ManyToManyField(blank=True, related_name='submittedAuthors', to='thesearchable.author'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='submittedBooks',
            field=models.ManyToManyField(blank=True, related_name='submittedBooks', to='thesearchable.book'),
        ),
    ]
