# Generated by Django 4.1.3 on 2023-06-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0022_author_submitteduser_book_submitteduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='favouriteBooks',
            field=models.ManyToManyField(blank=True, related_name='favouriteBooks', to='thesearchable.book'),
        ),
    ]
