# Generated by Django 4.1.3 on 2023-06-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0023_entry_source_userinfo_favouritebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entryPubDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
