# Generated by Django 4.1.3 on 2023-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0024_alter_entry_entrypubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
