# Generated by Django 4.1.3 on 2023-06-30 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0025_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favouriteusers',
            field=models.ManyToManyField(blank=True, related_name='bookfavouriteusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
