# Generated by Django 4.1.3 on 2023-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0026_book_favouriteusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
