# Generated by Django 4.1.3 on 2023-09-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesearchable', '0027_book_isbn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='countries',
            new_name='Country',
        ),
    ]
